### ISSUE TITLE
Blender 3.0 support?

### ISSUE THREAD

**Issue by jch-q** [DIYer22/bpycv#35]
Hi,

I get the following errors if I try the example script with Blender 3.0:

Eevee:

```
AttributeError: 'RenderSettings' object has no attribute 'tile_x'
```

Cycles:
```
    scene.view_layers["View Layer"].cycles, "use_denoising", False
KeyError: 'bpy_prop_collection[key]: key "View Layer" not found'
```

Are there solutions for this? Will Blender 3.0 get support?

**Comment by Lotemn102** [comment]
I also need this. How can i contribute?

**Comment by DIYer22** [comment]
@Lotemn102  I haven't started to fix it yet, you can get started directly and then send a pull request. If you have any questions or progress, you can reply under this issue, and I will keep an eye on it. And thank you for your kindness.

**Comment by lucasew** [comment]
I got it working on blender 3.1 for segmentation generation by removing those two lines

We use Nix to setup bpycv and blender to run everywhere we need so we solved this by applying a patch to the nixpkgs version

https://github.com/DIYer22/bpycv/blob/c5bcd56682f9b91dad777609c2d917b9a9d89b0f/bpycv/render_utils.py#L60
